EMAIL = "erenContract@test.com"
BASE_URL = "https://atrium.useinsider.com"
PARTNER = "inshoppingcart"
INSIDERID = "706cadeb-14ca-45ec-aa7c-bbc5ca4d1408"
SHOPIFYAPIKEY = ""
PARTNERSTORE = "insdev3"
SHOPIFY_BASE_URL = f"https://{PARTNERSTORE}.myshopify.com"
PRODUCTID= "7183556673579"
